### ISSUE TITLE
Use Dependabot to keep submodules up-to-date

### ISSUE THREAD

**Issue by greysteil** [eliotsykes/real-world-rails#64]
Hey @eliotsykes,

Thanks for this awesome resource!

I have a suggestion that I *think* is a good idea, but feel free to shoot me down.

Looks like you've got loads of submodules here, and periodically update them. Would it make sense to use [Dependabot](https://dependabot.com) to update them automatically? Here's the flow I'm thinking:
- Add this repo to Dependabot, and specify the language as "Git submodules"
- Set the automerge setting (in advanced options) to "All updates"
- Add CI to this repo (Dependabot won't automerge without it passing)
- Set the PR frequency to "weekly", because "daily" is probably a bit much

With that setup, Dependabot will create a set of PRs each week to update each repo to the latest commit, and merge them all.

What do you reckon?

**Comment by greysteil** [comment]
FYI, I got this working on my fork - check out https://github.com/greysteil/real-world-rails/pulls?q=is%3Apr+is%3Aclosed.

**Comment by eliotsykes** [comment]
Thanks for this @greysteil, ace idea and thanks for the contribution too. This will really help with keeping the project up-to-date. I'll setup Dependabot in the next month as you suggest. Going to leave this issue open until I get round to it.

**Comment by greysteil** [comment]
Awesome - thanks for a fantastic resource!

**Comment by eliotsykes** [comment]
Ahem, a little later than I intended, but its setup now. Thanks again @greysteil 👍 

(As it may be of interest, I opted for Cirrus CI as this was the first CI provider in GitHub Marketplace I'd found that used GitHub Apps instead of OAuth, with the permissions fine-grained enough so they only have access to this repo rather than all my repos. Fingers crossed the other providers will get round to doing this soon.)

**Comment by greysteil** [comment]
Nice! Thanks @eliotsykes!
